# shared/models.py
# This file defines the strict data schemas for communication between agents
# and for storage in Firestore. Pydantic is used as the primary guardrail
# for data validation, ensuring all data is structured and type-safe.

from pydantic import BaseModel, Field
from typing import List, Optional, Dict

# --- Shared Data Structures ---

class RoadCut(BaseModel):
    """
    Structured information about a single road or infrastructure blockage.
    Generated by the Damage Analysis Agent based on GEE vector data.
    """
    latitude: float
    longitude: float
    severity_score: int = Field(..., description="Score from 1 (minor) to 5 (critical/impassable).")
    description: str = Field(..., description="LLM-generated description of the damage.")

# --- Agent Input/Output Models ---

class RescueRequest(BaseModel):
    """
    Input document created by the Communication Router (Phase 0).
    This is the initial trigger for the entire workflow.
    """
    request_id: str = Field(..., description="Unique ID for the entire workflow.")
    region_name: str = Field(..., description="e.g., Cebu Province, Philippines")
    event_name: str = Field(..., description="e.g., Typhoon Kalmaegi")
    aoi_geojson: str = Field(..., description="GeoJSON boundary for the Area of Interest (AOI) as a JSON string.")
    timestamp: str = Field(..., description="ISO 8601 timestamp of when the request was created.")

class DamageReport(BaseModel):
    """
    Output document generated by the Damage Analysis Agent (Phase 1).
    This is the primary input for the Logistics Agent.
    """
    request_id: str = Field(..., description="Matches the parent RescueRequest ID.")
    flood_extent_km2: float = Field(..., description="GEE-derived flood extent in square kilometers.")
    damaged_buildings_count: int = Field(..., description="GEE-derived count of damaged buildings.")
    affected_population_estimate: int = Field(..., description="GEE-derived estimate of population in flooded zones.")
    critical_road_segments_geojson: Dict = Field(..., description="The raw GeoJSON of flooded road segments from GEE.")
    infrastructure_damage_summary: str = Field(..., description="LLM-generated narrative summary of infrastructure state.")
    road_cuts: List[RoadCut] = Field(default_factory=list, description="LLM-extracted list of critical road cuts with coordinates.")
    analysis_model: str = Field(..., description="The Vertex AI model ID used for the damage analysis.")
    timestamp: str = Field(..., description="ISO 8601 timestamp of when the report was generated.")
    
class ResourceAllocation(BaseModel):
    """
    Defines the quantity of a specific resource item allocated to a zone.
    """
    item: str = Field(..., description="e.g., Water Filters, MREs, Tents.")
    quantity: int = Field(..., description="The number of units allocated.")

class ReliefZone(BaseModel):
    """
    Defines a high-priority location for aid delivery identified by the Logistics Agent.
    """
    location_name: str = Field(..., description="Name of the town, village, or area.")
    latitude: float
    longitude: float
    priority_score: int = Field(..., description="Calculated priority score (1-5, 5 is highest).")
    estimated_affected_population: int = Field(..., description="Estimated population needing aid in this zone.")
    resource_needs: List[ResourceAllocation] = Field(default_factory=list, description="Specific resources allocated to this zone.")

class LogisticsPlan(BaseModel):
    """
    The final output document generated by the Logistics Agent (Phase 2).
    """
    request_id: str = Field(..., description="Matches the parent RescueRequest ID.")
    summary_narrative: str = Field(..., description="LLM-generated strategy and key takeaways for the resource allocation.")
    priority_zones: List[ReliefZone] = Field(default_factory=list, description="List of all defined priority relief zones.")
    key_logistics_challenges: List[str] = Field(default_factory=list, description="LLM-identified critical obstacles (e.g., road cuts, weather).")
    analysis_model: str = Field(..., description="The Vertex AI model ID used for the logistics planning.")
    timestamp: str = Field(..., description="ISO 8601 timestamp of when the plan was generated.")