# shared/models.py
# This file defines the strict data schemas for communication between agents
# and for storage in Firestore. Pydantic is used as the primary guardrail
# for data validation, ensuring all data is structured and type-safe.

from pydantic import BaseModel, Field
from typing import List, Optional, Dict, Any

# --- Shared Data Structures ---

class RoadCut(BaseModel):
    """
    Structured information about a single road or infrastructure blockage.
    Generated by the Damage Analysis Agent based on GEE vector data.
    """
    latitude: float
    longitude: float
    severity_score: int = Field(..., description="Score from 1 (minor) to 5 (critical/impassable).")
    description: str = Field(..., description="LLM-generated description of the damage.")

class RescueRequest(BaseModel):
    """
    CORRECTED MODEL: Input document created by the Communication Router (Phase 0).
    This only holds initial input and the AOI boundary.
    """
    request_id: str = Field(..., description="Unique ID for the entire workflow.")
    region_name: str = Field(..., description="e.g., Cebu Province, Philippines")
    event_name: str = Field(..., description="e.g., Typhoon Kalmaegi")
    # AOI boundary as a JSON string
    aoi_geojson: str = Field(..., description="GeoJSON boundary for the Area of Interest (AOI) as a JSON string.")
    timestamp: str = Field(..., description="ISO 8601 timestamp of when the request was initiated.")


class DamageReport(BaseModel):
    """
    The output document generated by the Damage Analysis Agent (Phase 1).
    This structure contains the fields that were incorrectly required by RescueRequest in your logs.
    """
    request_id: str = Field(..., description="Matches the parent RescueRequest ID.")
    analysis_region: str = Field(..., description="The region name used for the analysis.")
    flood_extent_km2: float = Field(..., description="Estimated flood area in square kilometers.")
    affected_population_estimate: int = Field(..., description="Estimated population within the affected area.")
    damaged_buildings_count: int = Field(..., description="Estimated count of buildings within the affected area.")
    critical_road_segments_geojson: Dict[str, Any] = Field(..., description="GeoJSON FeatureCollection of critical road cuts.")
    weather_impact: str = Field(..., description="Narrative summary of current or forecast weather impact.")
    aoi_geojson_layer: Dict[str, Any] = Field(..., description="The definitive GeoJSON of the AOI used for analysis.")
    summary_narrative: str = Field(..., description="LLM-generated summary of the damage findings.")
    critical_infrastructure_damage: List[str] = Field(default_factory=list, description="LLM-identified list of key infrastructure damage (e.g., hospitals, power plants).")
    road_cuts: List[RoadCut] = Field(default_factory=list, description="Structured list of specific road cuts.")
    analysis_model: str = Field(..., description="The Vertex AI model ID used for generation.")
    timestamp: str = Field(..., description="ISO 8601 timestamp of when the report was generated.")

# --- Logistics Models (Included for completeness) ---

class ResourceAllocation(BaseModel):
    resource_type: str = Field(..., description="e.g., 'Water Kits', 'Tents', 'Medical Supplies'.")
    unit_of_measure: str = Field(..., description="e.g., 'liters', 'units', 'boxes'.")
    units_allocated: int = Field(..., description="The number of units allocated.")

class ReliefZone(BaseModel):
    location_name: str = Field(..., description="Name of the town, village, or area.")
    latitude: float
    longitude: float
    priority_score: int = Field(..., description="Calculated priority score (1-5, 5 is highest).")
    estimated_affected_population: int = Field(..., description="Estimated population needing aid in this zone.")
    resource_needs: List[ResourceAllocation] = Field(default_factory=list, description="Specific resources allocated to this zone.")

class LogisticsPlan(BaseModel):
    request_id: str = Field(..., description="Matches the parent RescueRequest ID.")
    summary_narrative: str = Field(..., description="LLM-generated strategy and key takeaways for the resource allocation.")
    priority_zones: List[ReliefZone] = Field(default_factory=list, description="List of all defined priority relief zones.")
    key_logistics_challenges: List[str] = Field(default_factory=list, description="LLM-identified critical obstacles (e.g., road cuts, weather).")
    analysis_model: str = Field(..., description="The Vertex AI model ID used for the logistics planning.")
    timestamp: str = Field(..., description="ISO 8601 timestamp of when the plan was generated.")